# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Anthony Intino
description: "A place for my thoughts and experiences while learning Android"
keywords: "Jekyll, theme, free, SEO, blog, web, Android, developer, engineer, android developer, android engineer"
url: http://int-a.github.io
baseurl: ""
# baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/int-a
disqus_shortname: "int-a"
disqus_site_shortname: "int-a"

# Author settings
author:
  name      : Anthony Intino
  job       : Software Engineer
  bio       : "Programmer, Traveler, Guitarist, Android Enthusiast. I'm learning Android development and loving it more and more as I do."
  thumb     : /images/author.png
  email     : anthony.intino@gmail.com
  url       : http://int-a.github.io
  github    : http://github.com/int-a
  twitter   :
  facebook  :
  linkedin  : https://www.linkedin.com/in/afi3rd/

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: resume
    title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
